// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adullam '26: The Pillar of Our Faith | C&S Movement Church",
  description:
    "Join us for Adullam '26: The Pillar of Our Faith at The Mandate Arena, Lagos, from August 13th - 15th. Hosted by the Cherubim and Seraphim Movement Church.",
  metadataBase: new URL("https://adullam2026.vercel.app/"), // Replace with your actual domain
  openGraph: {
    title: "Adullam '26: The Pillar of Our Faith",
    description:
      "Experience spiritual growth at Adullam '26. August 13th-15th at The Mandate Arena, Igando, Lagos.",
    images:
      "https://res.cloudinary.com/dcgxi0szf/image/upload/v1781946450/Adullam_yfmlgw.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // JSON-LD Structured Data for Event SEO
  const eventSchema = {
    "@context": "https://schema.org",
    "@type": "Event",
    name: "Adullam '26: The Pillar of Our Faith",
    startDate: "2026-08-13",
    endDate: "2026-08-15",
    eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
    location: {
      "@type": "Place",
      name: "The Mandate Arena",
      address: {
        "@type": "PostalAddress",
        streetAddress: "31 Balogun Ketiku Street, Igando",
        addressLocality: "Lagos",
        addressCountry: "NG",
      },
    },
    image:
      "https://res.cloudinary.com/dcgxi0szf/image/upload/v1781946450/Adullam_yfmlgw.png",
    description:
      "Annual program hosted by C&S Movement Church, Christ Royal Mandate District Headquarters.",
  };

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script
          id="event-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(eventSchema) }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
